version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    environment:
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_PORT: 5432
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST_DOCKER:-postgres}
    depends_on:
      - postgres
    networks:
      - journey


  postgres:
    image: "postgres:16.2-alpine3.19"
    container_name: api-db
    # restart: unless-stopped
    ports:
      - ${JOURNEY_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
    # volumes:
    #   - db:/var/lib/postgresql/data
    networks:
      - journey

networks:
  journey:
    driver: bridge
    